<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PolicyModule.Persistence</AssemblyName>
    <RootNamespace>PolicyModule.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../EventSourcing/Core/Core.csproj" />
    <ProjectReference Include="../../../EventSourcing/Persistence.Interfaces/Persistence.Interfaces.csproj" />
    <ProjectReference Include="../../../EventSourcing/Shared/Shared.csproj" />
    <ProjectReference Include="../../SharedModule/Constants/Constants.csproj" />
    <ProjectReference Include="../Domain/Domain.csproj" />
    <ProjectReference Include="../Persistence.Interfaces/Persistence.Interfaces.csproj" />
  </ItemGroup>

</Project>
