<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MemoryModule.Persistence.Interfaces</AssemblyName>
    <RootNamespace>MemoryModule.Persistence.Interfaces</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../ActionModule/Shared/Shared.csproj" />
    <ProjectReference Include="../../../EmbeddingModule/EmbeddingModule.csproj" />
    <ProjectReference Include="../../../EventSourcing/Shared/Shared.csproj" />
    <ProjectReference Include="../Domain/Domain.csproj" />
  </ItemGroup>

</Project>
