// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using PostgreSqlModule;

#nullable disable

namespace PostgreSqlModule.Migrations.EventSourcing
{
    [DbContext(typeof(PostgreSqlEventSourcingDbContext))]
    [Migration("20260824225811_AddKnowledgeSearchProjection")]
    partial class AddKnowledgeSearchProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventSourcing.Persistence.Models.SerializedEventPayload", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EventExecutor")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedJsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AggregateId", "OrderNumber");

                    b.ToTable("SerializedEventPayload");
                });

            modelBuilder.Entity("EventSourcing.Persistence.Models.SerializedPayloadMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("ExecutionAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("SerializedEventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedEventExecutionInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("SerializedPayloadMessage");
                });

            modelBuilder.Entity("EventSourcing.Persistence.Models.UniqueEventConstraint", b =>
                {
                    b.Property<byte[]>("ConstraintHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .IsFixedLength();

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConstraintHash");

                    b.ToTable("UniqueEventConstraints", (string)null);
                });

            modelBuilder.Entity("FeatureModule.Persistence.Models.FeatureSearchEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureAggregateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("ProjectedOrderNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureAggregateId")
                        .IsUnique();

                    b.HasIndex("SearchText")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PlanCount", "FeatureAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("RecordCount", "FeatureAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("NormalizedName", "Name", "FeatureAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("ProjectId", "PlanCount", "FeatureAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("ProjectId", "RecordCount", "FeatureAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("ProjectId", "NormalizedName", "Name", "FeatureAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("FeatureSearchEntries", (string)null);
                });

            modelBuilder.Entity("FeatureModule.Persistence.Models.FeatureSummaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureAggregateId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("FeatureSummaries");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.GeneralPolicyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .IsUnique();

                    b.ToTable("GeneralPolicyTexts");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.PolicyProjectSummaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryPathsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAggregateId")
                        .IsUnique();

                    b.HasIndex("ProjectName")
                        .IsUnique();

                    b.ToTable("PolicyProjectSummaries");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.ProjectPolicyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAggregateId")
                        .IsUnique();

                    b.ToTable("ProjectPolicyTexts");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.ProjectPolicyTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAggregateId", "TopicName")
                        .IsUnique();

                    b.ToTable("ProjectPolicyTopics");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.TopicPolicyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicName")
                        .IsUnique();

                    b.ToTable("TopicPolicyTexts");
                });

            modelBuilder.Entity("PostgreSqlModule.FeatureResearchSearchEntry", b =>
                {
                    b.Property<Guid>("FeatureAggregateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchDiscoveryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "FeatureName", "Title", "SourceType", "SourceReference", "Text" });

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeatureAggregateId", "ResearchDiscoveryId", "ChunkIndex");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("FeatureResearchSearchEntries", (string)null);
                });

            modelBuilder.Entity("PostgreSqlModule.KnowledgeSearchEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<Guid>("OwnerAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SourceType", "SourceKey", "SearchableMetadata", "Text" });

                    b.Property<string>("SearchableMetadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("OwnerType", "OwnerAggregateId", "SourceType", "SourceKey", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("KnowledgeSearchEntries", (string)null);
                });

            modelBuilder.Entity("PostgreSqlModule.MemorySearchEntry", b =>
                {
                    b.Property<Guid>("MemoryAggregateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<int>("HookIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<string>("HookEventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PromptStartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "HookEventName", "Text" });

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryAggregateId", "PromptId", "HookIndex", "ChunkIndex");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("PromptStartTimestamp");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("ThreadId");

                    b.ToTable("MemorySearchEntries", (string)null);
                });

            modelBuilder.Entity("PostgreSqlModule.MemorySummaryEntry", b =>
                {
                    b.Property<Guid>("MemoryAggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FirstPromptTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPromptTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PromptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SummaryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryAggregateId");

                    b.HasIndex("LastActivityTimestamp");

                    b.HasIndex("ThreadId");

                    b.ToTable("MemorySummaryEntries", (string)null);
                });

            modelBuilder.Entity("PostgreSqlModule.SkillSearchEntry", b =>
                {
                    b.Property<Guid>("SkillAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePath")
                        .HasColumnType("text");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SkillName", "SourcePath", "Text" });

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SkillAggregateId", "SourcePath", "ChunkIndex");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SkillName");

                    b.ToTable("SkillSearchEntries", (string)null);
                });

            modelBuilder.Entity("SkillsModule.Persistence.Models.SkillListEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProjectedOrderNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SkillAggregateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SearchText")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SkillAggregateId")
                        .IsUnique();

                    b.HasIndex("AttachmentCount", "SkillAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("ReferenceCount", "SkillAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("NormalizedName", "Name", "SkillAggregateId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("SkillListEntries", (string)null);
                });

            modelBuilder.Entity("SkillsModule.Persistence.Models.SkillListTagEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NormalizedTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillListEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTag", "SkillListEntryId");

                    b.HasIndex("SkillListEntryId", "NormalizedTag")
                        .IsUnique();

                    b.ToTable("SkillListTags", (string)null);
                });

            modelBuilder.Entity("SkillsModule.Persistence.Models.SkillSummaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SkillAggregateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SkillAggregateId")
                        .IsUnique();

                    b.ToTable("SkillSummaries");
                });

            modelBuilder.Entity("SkillsModule.Persistence.Models.SkillListTagEntry", b =>
                {
                    b.HasOne("SkillsModule.Persistence.Models.SkillListEntry", null)
                        .WithMany("Tags")
                        .HasForeignKey("SkillListEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillsModule.Persistence.Models.SkillListEntry", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
