// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using PostgreSqlModule;

#nullable disable

namespace PostgreSqlModule.Migrations.EventSourcing
{
    [DbContext(typeof(PostgreSqlEventSourcingDbContext))]
    [Migration("20260808203356_AddPolicyProjectSummaries")]
    partial class AddPolicyProjectSummaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventSourcing.Persistence.Models.SerializedEventPayload", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EventExecutor")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedJsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AggregateId", "OrderNumber");

                    b.ToTable("SerializedEventPayload");
                });

            modelBuilder.Entity("EventSourcing.Persistence.Models.SerializedPayloadMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExecutionAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("SerializedEventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedEventExecutionInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("SerializedPayloadMessage");
                });

            modelBuilder.Entity("EventSourcing.Persistence.Models.UniqueEventConstraint", b =>
                {
                    b.Property<byte[]>("ConstraintHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .IsFixedLength();

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConstraintHash");

                    b.ToTable("UniqueEventConstraints", (string)null);
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.GeneralPolicyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .IsUnique();

                    b.ToTable("GeneralPolicyTexts");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.PolicyProjectSummaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryPathsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAggregateId")
                        .IsUnique();

                    b.HasIndex("ProjectName")
                        .IsUnique();

                    b.ToTable("PolicyProjectSummaries");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.ProjectPolicyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAggregateId")
                        .IsUnique();

                    b.ToTable("ProjectPolicyTexts");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.ProjectPolicyTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAggregateId", "TopicName")
                        .IsUnique();

                    b.ToTable("ProjectPolicyTopics");
                });

            modelBuilder.Entity("PolicyModule.Persistence.Models.TopicPolicyText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicName")
                        .IsUnique();

                    b.ToTable("TopicPolicyTexts");
                });

            modelBuilder.Entity("PostgreSqlModule.MemorySearchEntry", b =>
                {
                    b.Property<Guid>("MemoryAggregateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<int>("HookIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<string>("HookEventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PromptStartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "HookEventName", "Text" });

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryAggregateId", "PromptId", "HookIndex", "ChunkIndex");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("PromptStartTimestamp");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("ThreadId");

                    b.ToTable("MemorySearchEntries", (string)null);
                });

            modelBuilder.Entity("PostgreSqlModule.SkillSearchEntry", b =>
                {
                    b.Property<Guid>("SkillAggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePath")
                        .HasColumnType("text");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SkillName", "SourcePath", "Text" });

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SkillAggregateId", "SourcePath", "ChunkIndex");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SkillName");

                    b.ToTable("SkillSearchEntries", (string)null);
                });

            modelBuilder.Entity("SkillsModule.Persistence.Models.SkillSummaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SkillAggregateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SkillAggregateId")
                        .IsUnique();

                    b.ToTable("SkillSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
