// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreSqlModule;

#nullable disable

namespace PostgreSqlModule.Migrations.EventSourcing
{
    [DbContext(typeof(PostgreSqlEventSourcingDbContext))]
    partial class PostgreSqlEventSourcingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventSourcing.Persistence.Models.SerializedEventPayload", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EventExecutor")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedJsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AggregateId", "OrderNumber");

                    b.ToTable("SerializedEventPayload");
                });

            modelBuilder.Entity("EventSourcing.Persistence.Models.SerializedPayloadMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExecutionAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("SerializedEventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerializedEventExecutionInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("SerializedPayloadMessage");
                });

            modelBuilder.Entity("EventSourcing.Persistence.Models.UniqueEventConstraint", b =>
                {
                    b.Property<byte[]>("ConstraintHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .IsFixedLength();

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstraintName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StateMachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConstraintHash");

                    b.ToTable("UniqueEventConstraints", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
