<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ActionModule.Shared</AssemblyName>
    <RootNamespace>ActionModule.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../EventSourcing/Shared/Shared.csproj" />
  </ItemGroup>

</Project>
