<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SharedModule.Constants</AssemblyName>
    <RootNamespace>SharedModule.Constants</RootNamespace>
  </PropertyGroup>

</Project>
