// <auto-generated />
using Api.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations.Settings;

[DbContext(typeof(SettingsDbContext))]
partial class SettingsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.16")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Api.Settings.Settings", settings =>
        {
            settings.Property<int>("Id")
                .ValueGeneratedNever()
                .HasColumnType("integer");

            settings.Property<int>("Theme")
                .HasColumnType("integer");

            settings.HasKey("Id");

            settings.ToTable(
                "Settings",
                table => table.HasCheckConstraint(
                    "CK_Settings_Singleton",
                    "\"Id\" = 1"
                )
            );
        });
#pragma warning restore 612, 618
    }
}
