<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SkillsModule.MCP</AssemblyName>
    <RootNamespace>SkillsModule.MCP</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../ActionModule/Shared/Shared.csproj" />
    <ProjectReference Include="../Application/Application.csproj" />
    <ProjectReference Include="../Domain/Domain.csproj" />
  </ItemGroup>

</Project>
