<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.16">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DomainsModules/MemoryModule/Persistence.Interfaces/Persistence.Interfaces.csproj" />
    <ProjectReference Include="../DomainsModules/MemoryModule/Persistence/Persistence.csproj" />
    <ProjectReference Include="../DomainsModules/PolicyModule/Persistence.Interfaces/Persistence.Interfaces.csproj" />
    <ProjectReference Include="../DomainsModules/PolicyModule/Persistence/Persistence.csproj" />
    <ProjectReference Include="../DomainsModules/SkillsModule/Application/Application.csproj" />
    <ProjectReference Include="../DomainsModules/SkillsModule/Persistence/Persistence.csproj" />
    <ProjectReference Include="../DomainsModules/SkillsModule/Persistence.Interfaces/Persistence.Interfaces.csproj" />
    <ProjectReference Include="../EventSourcing/Persistence/Persistence.csproj" />
    <ProjectReference Include="../EventSourcing/Shared/Shared.csproj" />
  </ItemGroup>

</Project>
