<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SkillsModule.API</AssemblyName>
    <RootNamespace>SkillsModule.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../ActionModule/API/API.csproj" />
    <ProjectReference Include="../../../ActionModule/Shared/Shared.csproj" />
    <ProjectReference Include="../../../EventSourcing/Core/Core.csproj" />
    <ProjectReference Include="../../../EventSourcing/Persistence.Interfaces/Persistence.Interfaces.csproj" />
    <ProjectReference Include="../Application/Application.csproj" />
    <ProjectReference Include="../Domain/Domain.csproj" />
  </ItemGroup>

</Project>
