<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FeatureModule.Persistence.Interfaces</AssemblyName>
    <RootNamespace>FeatureModule.Persistence.Interfaces</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../ActionModule/Shared/Shared.csproj" />
    <ProjectReference Include="../../../EventSourcing/Shared/Shared.csproj" />
    <ProjectReference Include="../Contracts/Contracts.csproj" />
  </ItemGroup>

</Project>
